#!/bin/bash -
ghdl analyze --workdir=build src/fft_types.vhdl
cd generate
make
cd ..
./do src/butterfly_unit/c_mult.vhdl src/butterfly_unit/bfu.vhdl src/memory/ram.vhdl src/memory/ram_group.vhdl generate/grom.vhdl src/management_unit/counter.vhdl src/management_unit/mu.vhdl src/fft.vhdl generate/fft_tb.vhdl
