#!/bin/bash -
ghdl -a --work=xil_defaultlib src/fft_types.vhdl
./do src/c_mult.vhdl src/butterfly.vhdl src/ram.vhdl src/ram_group.vhdl generate/grom.vhdl src/counter.vhdl src/management_unit.vhdl src/fft.vhdl generate/fft_tb.vhdl