
gen_twiddle: gen_twiddle.o
	gcc gen_twiddle.o -o gen_twiddle -lm
gen_twiddle.o: gen_twiddle.c 
	gcc -c -o gen_twiddle.o gen_twiddle.c

gen_tb: gen_tb.o
	gcc gen_tb.o -o gen_tb
gen_tb.o: gen_tb.c
	gcc -c -o gen_tb.o gen_tb.c
